apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-boot-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-spring-boot-app
  template:
    metadata:
      labels:
        app: sample-spring-boot-app
    spec:
      # imagePullSecrets is at the Pod Spec level (same level as containers)
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: sample-spring-boot-app
        image: 098072157119.dkr.ecr.ap-south-1.amazonaws.com/sample-spring-boot-app
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits: # Good practice to include limits for stability
            memory: "1Gi"
            cpu: "500m"
        # Probes must be indented INSIDE the specific container block
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
              #initialDelaySeconds: 30 # Give Spring Boot time to start
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
              #initialDelaySeconds: 30
          periodSeconds: 10
