apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-boot-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-spring-boot-app
  template:
    metadata:
      labels:
        app: sample-spring-boot-app
    spec:
      containers:
      - name: sample-spring-boot-app
        image: 098072157119.dkr.ecr.ap-south-1.amazonaws.com/sample-spring-boot-app
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"

      imagePullSecrets:
      - name: ecr-secret
