apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-spring-boot-app
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-spring-boot-app
  template:
    metadata:
      labels:
        app: sample-spring-boot-app
    spec:
      containers:
      - name: sample-spring-boot-app
        image: YOUR_AWS_ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/sample-spring-boot-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
