apiVersion: v1
kind: Service
metadata:
  name: sample-spring-boot-app
  namespace: qa
spec:
  selector:
    app: sample-spring-boot-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
